version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: loong
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
